#if !canImport(ObjectiveC)
import XCTest

extension UserDefaultsExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UserDefaultsExtensionsTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(UserDefaultsExtensionsTests.__allTests__UserDefaultsExtensionsTests),
    ]
}
#endif
